name: spend_wise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get:
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  pinput: ^5.0.0
  flutter_svg: ^2.0.9
  iconsax: ^0.0.8
  flutter_expandable_fab: ^2.3.0
  animated_toggle_switch: ^0.8.3
  fl_chart: ^0.69.0
  textfield_tags: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
